language: node_js
node_js:
- '8'
install:
- npm install -g npm
- npm ci
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  on:
    branch: master
  skip_cleanup: true
  api_key:
    secure: YHY9mqiLNTUe3f1plLGaK2soC9YcgXFxz8k6k690tMduq5er8oKKeE7neHWARh1yh4O9M/CzWg5pPPlHAFWL3bqyN+TtAnw7gB8hiMX8mduU7C6w5eUwlMTbObbpsaFn4HAq6HXPX8/Ksm00QfqmapZpdOmzcknik3EWdjGMOoHZMr9DPc4XkM6xUCZF8li1j8KMByrefj8Z0j6s2MPt4GOdAGSm/rXwIKMK8W6LBXQ0SR+rACebSP/RDEVOrX1Zvj+OBx0bC6Ig32XeWAYyLmNEeMaAf8n4qIS+dRYlDjRUzAWnl1Wiiscar/0xFe+bKOmdUS5x0vVeMhp3tKO8vsJPXdW1Od5lRRy3RxSbuexRBU8soubvR6D186fjJVqZCTfYZv5f0LVhTBYclr0lKvtYVbTKa6RNcb5UF7L9cfY2/f33D92tpORf3qRnUoXDHZFP3cBvHRGPVv2ezKbwd7TNPpghYxd9vnlwXci6vEZkrqk4STxxjqP/uA4YTHGdkaBf3a+qMbzGYxmph0zDMxL4ji4nA+Wc0kGisFz0TK4Z1uMQvNhYCU625t3UhBxOS88ylCc+BYAqAST3FZnNLHC6yjtj0zi7jpOBPokmnVijkB55tfavepCKawMZOTKuRnkmHHdjspKVYJSm9AUHVcCTC0b/dpVntyNxqigAF2o=
