language: node_js
node_js:
- '8'
install:
- npm install -g npm
- npm ci
script:
- npm test
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  on:
    branch: master
  skip_cleanup: true
  api_key:
    secure: H/buMb/Bi6bWkasAHkgvr/O3ZuoY8hEKVRIduu4VWyZ9wb4x60uD0n+uU/po02miEkwg11nLXFsbBVzpnAKvwxPEX/lHJ8X0qluvxz49Qz6UpFV5dVVX+/rVcEm+4uqzBDoGLAiNvRXykwShB0CqVUnkjSp+cx+qYOgzlynjxUjD/26o4YKtxCQkVafAmGeeV4re7Yz9cYGVSpzVB3XhihFpROzAaq5pQ5T9cfhW+e8W+NiO6OJxFyOXMwvesX8bV3Nl55ex7+1Q3zoVF3AlIdQgL9nmgwfPXsMdckjAMDXypyhpxU6CImrFOZxmoVqG1vfKiEhIG3/o4dbCvzK0A1evCGx37YzyOlGP4wBVlMYrSReDBdpEqTU6KVzF/9sm6sQutzztHALv2NoU2APhBYIssrwai3352K7lx+7WWUHbzGuoSjctU+zURM0ZftoGGz9pGLmRDFON7AVLbQlC72x5yLjrkVJex6FPI3oMLUsQlzWu+82/EKF72eGcid1nT67gQJZDfyMv0tmnnrROLfWObf3X20eR3lY5xFpBJDevWoEegdPG2QyGwv8RXEn3Kfkmu2UKJzsDIyPVt5Iwr9J1DQDPFv3kmleys3IRKUMaMRj9vT6K6+M4TOk61CPr25LhylhNLlEuDrbU13pp4MT8KeB4kcSt8k7zds8b4Mw=

