language: node_js
node_js:
- '8'
install:
- npm install -g npm
- npm ci
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  on:
    branch: master
  skip_cleanup: true
  api_key:
    secure: QdbLcs9gTsEAkbTm3x9L2Fazmp8E85xO5C8JPEuvIe9ZCilcw4VUUmf/QiYJzOK2J6aMA1uim0GuMo+DQOvLeDT3ts3kr2vaWuw32EVuz7F4RHsm0o3gFQKE4mkBlLNg4oaW2M73t9Ok3GBVle7tcjhKy8BwGizpSSnf4aolQHvhBUwJQEuUBRBtPUdeyd7S7Uea3f007BQ+v7jF3KxOCLQaen6LhxGaD4BLOsW+wloe7RglK5FPsilCBkWAwTft4Q7XsjIcKARrPUiiq4ftY07cuxELwMAyG9ojmdBvwbd5SglE6AM2J+c8FuZvgH3ow8Kny0C6lFeqC8LhqaJgoiitq+fQ8tgUR17V9obcyXo7O2cxfxRzvAiraB4NTDww9McEcGEwU3umtnS91y7M+/vBaxY6FJSIcIopg8RhtGiHZw497UFYHgxJqxbYE42jZw6WjEM1clwDEBebR+ipVGCDgvjpQaLz/TJZengVndMHoh4Yb+ArTEv0Os0IGfp1UOjWTbrLcYKPsgiA0SnO1YrZ3qdKD12qWfbPneyuX4iMhMd0eG5nm8wuzNieTlibDCrSmbkul53kiRVJDEX6ftz9BNgLinZ5WepXNmvr5mZb3LfzuYq9sylgJ/5LtTsAaXX87Ho2lP5JR25FNYPMlbNba3lQMx6WwaiPxh/L000=
