language: node_js
node_js:
- '8'
install:
- npm install -g npm
- npm ci
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  on:
    branch: master
  skip_cleanup: true
  api_key:
    secure: V31LusgDXxq8lIa7Ep0Mh0VC/zjLp3WShP0gpY2fFMbneUKov5859oWEPA/4R0fx/S72808E2Rj7/4pExl249pQwFTFBXb2d0oTL5MT85zyJYrfguAcJFgiOBtvnr/OGnWXQxPxZmqxe1XAduIGDD8xUwIkW16hTbQvZNgT0Fb6x36USFMcQokw+u5ObtQENLYArdyNW/lvSXPRSkh38FV9LloAYcpwUZv82oBR2hI8yG2cNq9eUCymVlmhaA/bdySvHda+6Wib1GraJb9lyhVm68LK1TaMhJtwWn5ocZDYhJBETQXNWL97kydlgRrrIzbPElldF6tcIlFeqoxKYL5HUTjGZHd4Luikrtjolc9XJ4EZLrWJl532G5A/d6oF17MjHMsjoCcqPnXdr+c3EwYX6+/H2ZE/S0KpP1xs1tGpK0hh6c+KZFM7E8AfHBdahv/Feq1Q21pCYFrAzCoXZzycB5GFlDe32m9DaUeZrZ2XquI7Dn5/z92ey8Io+j/zNpxdWIL/+GZJCTrfXUjGVk4PAdQow8nX7zFO45tPDAnkfdyUrx8mwfAIidl1cgVY7ZLPShCwGHHewBAEi09PxCMNB+XXy/25PidpWqmUN63AGK9wCfhH/T3ypPhc0ZlofkMy3bhAz7TbKONY57YbTD19N6HTwItQrnIyoRxT3XwQ=
